### ISSUE TITLE
Docs, bad, extesnion not works

### ISSUE THREAD

**Issue by TamasSzalisznyi** [MarketSquare/robotframeworkguides#39]
Hi!

Just starting to explore robotframework, but as per the website tell me installing the two recommended extensions:

Name: RobotCode - Robot Framework Support
Id: d-biehl.robotcode
Description: Robot Framework IntelliSense, linting, test execution and debugging, code formatting, refactoring, and many more
Version: 0.69.0
Publisher: Daniel Biehl
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=d-biehl.robotcode
and
Name: Robot Framework Language Server
Id: robocorp.robotframework-lsp
Description: VSCode extension support for Robot Framework
Version: 1.11.0
Publisher: Robocorp
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=robocorp.robotframework-lsp
resulting in an error with one of the example script, the insurance one.
attaching a few screenshot.

RobotFrameWork: 7.0
Python: 3.12.1
OS: win32/AMD64, 10.0.22631

![image](https://github.com/MarketSquare/robotframeworkguides/assets/55410553/79ad3dca-6930-4712-8313-a219bafb0f23)
![image](https://github.com/MarketSquare/robotframeworkguides/assets/55410553/abfa3f2e-55b4-42d5-bcf3-0cba6e334fb3)

According to Robocorp dev its not recomended and expected. 
Please update the docs:  https://docs.robotframework.org/docs/getting_started/ide#visual-studio-code

The good extesion should be: Robocorp code:
Name: Robocorp Code
Id: robocorp.robocorp-code
Description: Extension for Robot development in VSCode using Robocorp
Version: 1.15.1
Publisher: Robocorp
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=robocorp.robocorp-code

But still, after the fix, no keyword is recognized.

Maybe the next potential user have more success, for me it was enough from robot.

**Comment by manykarim** [comment]
Hey there,
thank you for your feedback.

Unfortunately Robocorp (which is not related to the Robot Framework Foundation) has stopped the maintenance of their Robot Framework Language Server extension. So it is no longer working for the latest Robot Framework 7.0.
And as you recommended, it needs to be removed from the Docs site.

I recommend to only use the RobotCode Extension which we also mention in the Docs and that you installed.
The problems that you experienced might be caused by the fact that you installed both extensions in parallel.

As we pointed out on the Docs:
![image](https://github.com/MarketSquare/robotframeworkguides/assets/61293164/eb00d6d9-ee23-4896-9dc5-c505b53c6c22)
https://docs.robotframework.org/docs/getting_started/ide#visual-studio-code-extensions

Hopefully you find the time to give Robot Framework another try with a proper setup.
I'm always happy to help and also the community at https://forum.robotframework.org/ and https://rf-invite.herokuapp.com/ is very friendly and helpful
